### ISSUE TITLE
[Feature Request] More data

### ISSUE THREAD

**Issue by adamrzanek** [Nubzor/homebridge-airly-v2#3]
Cześć! Myślisz, że jest możliwe by w tym pluginie zaimplementować inne dane z airly? Temperaturę, wilgotność itd?
I jeszcze jedno - mam uknown error niestety kilka razy dziennie. 
<img width="557" alt="Screen Shot 2020-11-23 at 12 53 27" src="https://user-images.githubusercontent.com/65444919/99959370-30f50480-2d8b-11eb-9d43-250ac5d1dcba.png">

**Comment by Nubzor** [comment]
@adamrzanek I haven't planned to do any further development of this plugin unless there will be a high interest in it. 

Please upgrade to version 1.1.0 and check whether the "Airly Network or Unknown Error" persists. Recently, I've introduced a bunch of improvements to the plugin and it seems to be more stable.

**Comment by Nubzor** [comment]
@adamrzanek I spend some time during the winter break to enhance the plugin with additional characteristics as per your request. Since 2.0.0 you can use temperature, humidity and pressure, please be advised that the last one is a custom characteristic which is not available through `Homebride` or `Home` app. You can access such characteristic in an app that supports these - like Eve or Controller. 

Also, I improved logging to make it easier to debug any kind of errors, let me know if the error persist.

Closing this one as resolved. Cheers!
