### ISSUE TITLE
Does this plug in work in US?

### ISSUE THREAD

**Issue by todesto** [Nubzor/homebridge-airly-v2#4]
I installed but says accessory not responding. 
Log shows airly is working, so it looks like I am getting no data pulled from airly on my geo location.

**Comment by kylerove** [comment]
Same issue here

**Comment by benov84** [comment]
Not working for me too

**Comment by Nubzor** [comment]
Since the second version > 2.0.0 the plugin should work with the US, however, you should be aware that the Airly (data provider) coverage across US isn't as good as in Europe. 

Please upgrade to newest version of the plugin and try to use it either by `nearest` or `locationId` approach. 

Let me know if there is anything I could do to improve your experience. Cheers!
